/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FlashRouteImport } from './routes/flash'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AftercareRouteImport } from './routes/aftercare'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnquiryThanksRouteImport } from './routes/enquiry.thanks'
import { Route as AuthenticatedEnquiriesRouteImport } from './routes/_authenticated/enquiries'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as FlashIdClaimRouteImport } from './routes/flash.$id.claim'

const FlashRoute = FlashRouteImport.update({
  id: '/flash',
  path: '/flash',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AftercareRoute = AftercareRouteImport.update({
  id: '/aftercare',
  path: '/aftercare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryThanksRoute = EnquiryThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => EnquiryRoute,
} as any)
const AuthenticatedEnquiriesRoute = AuthenticatedEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FlashIdClaimRoute = FlashIdClaimRouteImport.update({
  id: '/$id/claim',
  path: '/$id/claim',
  getParentRoute: () => FlashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aftercare': typeof AftercareRoute
  '/auth': typeof AuthRoute
  '/enquiry': typeof EnquiryRouteWithChildren
  '/estimate': typeof EstimateRoute
  '/flash': typeof FlashRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enquiries': typeof AuthenticatedEnquiriesRoute
  '/enquiry/thanks': typeof EnquiryThanksRoute
  '/flash/$id/claim': typeof FlashIdClaimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aftercare': typeof AftercareRoute
  '/auth': typeof AuthRoute
  '/enquiry': typeof EnquiryRouteWithChildren
  '/estimate': typeof EstimateRoute
  '/flash': typeof FlashRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enquiries': typeof AuthenticatedEnquiriesRoute
  '/enquiry/thanks': typeof EnquiryThanksRoute
  '/flash/$id/claim': typeof FlashIdClaimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aftercare': typeof AftercareRoute
  '/auth': typeof AuthRoute
  '/enquiry': typeof EnquiryRouteWithChildren
  '/estimate': typeof EstimateRoute
  '/flash': typeof FlashRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/enquiries': typeof AuthenticatedEnquiriesRoute
  '/enquiry/thanks': typeof EnquiryThanksRoute
  '/flash/$id/claim': typeof FlashIdClaimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aftercare'
    | '/auth'
    | '/enquiry'
    | '/estimate'
    | '/flash'
    | '/dashboard'
    | '/enquiries'
    | '/enquiry/thanks'
    | '/flash/$id/claim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aftercare'
    | '/auth'
    | '/enquiry'
    | '/estimate'
    | '/flash'
    | '/dashboard'
    | '/enquiries'
    | '/enquiry/thanks'
    | '/flash/$id/claim'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aftercare'
    | '/auth'
    | '/enquiry'
    | '/estimate'
    | '/flash'
    | '/_authenticated/dashboard'
    | '/_authenticated/enquiries'
    | '/enquiry/thanks'
    | '/flash/$id/claim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AftercareRoute: typeof AftercareRoute
  AuthRoute: typeof AuthRoute
  EnquiryRoute: typeof EnquiryRouteWithChildren
  EstimateRoute: typeof EstimateRoute
  FlashRoute: typeof FlashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/flash': {
      id: '/flash'
      path: '/flash'
      fullPath: '/flash'
      preLoaderRoute: typeof FlashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aftercare': {
      id: '/aftercare'
      path: '/aftercare'
      fullPath: '/aftercare'
      preLoaderRoute: typeof AftercareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry/thanks': {
      id: '/enquiry/thanks'
      path: '/thanks'
      fullPath: '/enquiry/thanks'
      preLoaderRoute: typeof EnquiryThanksRouteImport
      parentRoute: typeof EnquiryRoute
    }
    '/_authenticated/enquiries': {
      id: '/_authenticated/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof AuthenticatedEnquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/flash/$id/claim': {
      id: '/flash/$id/claim'
      path: '/$id/claim'
      fullPath: '/flash/$id/claim'
      preLoaderRoute: typeof FlashIdClaimRouteImport
      parentRoute: typeof FlashRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnquiriesRoute: typeof AuthenticatedEnquiriesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnquiriesRoute: AuthenticatedEnquiriesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EnquiryRouteChildren {
  EnquiryThanksRoute: typeof EnquiryThanksRoute
}

const EnquiryRouteChildren: EnquiryRouteChildren = {
  EnquiryThanksRoute: EnquiryThanksRoute,
}

const EnquiryRouteWithChildren =
  EnquiryRoute._addFileChildren(EnquiryRouteChildren)

interface FlashRouteChildren {
  FlashIdClaimRoute: typeof FlashIdClaimRoute
}

const FlashRouteChildren: FlashRouteChildren = {
  FlashIdClaimRoute: FlashIdClaimRoute,
}

const FlashRouteWithChildren = FlashRoute._addFileChildren(FlashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AftercareRoute: AftercareRoute,
  AuthRoute: AuthRoute,
  EnquiryRoute: EnquiryRouteWithChildren,
  EstimateRoute: EstimateRoute,
  FlashRoute: FlashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
